"""add

Revision ID: 002e0f336cd3
Revises:
Create Date: 2021-10-26 01:03:37.674067

"""

# revision identifiers, used by Alembic.
revision = '002e0f336cd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
