"""add

Revision ID: 165ad6bc3351
Revises: 002e0f336cd3
Create Date: 2021-10-26 01:04:27.744690

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '165ad6bc3351'
down_revision = '002e0f336cd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homeworks',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('text', sa.String(length=50), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=True),
                    sa.Column('deadline', sa.Interval(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('students',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('last_name', sa.String(length=50),
                              nullable=False),
                    sa.Column('first_name', sa.String(length=50),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('teachers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('last_name', sa.String(length=50),
                              nullable=False),
                    sa.Column('first_name', sa.String(length=50),
                              nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('solutions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('homework', sa.Integer(), nullable=True),
                    sa.Column('solution', sa.String(length=100),
                              nullable=False),
                    sa.Column('author', sa.Integer(), nullable=True),
                    sa.Column('created', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['author'], ['students.id'], ),
                    sa.ForeignKeyConstraint(['homework'], ['homeworks.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solutions')
    op.drop_table('teachers')
    op.drop_table('students')
    op.drop_table('homeworks')
    # ### end Alembic commands ###
